/*
 * HAPA Vehicle Rental System - Administrator Dashboard
 * Main interface for system administrators providing access to all management functions
 * Features navigation menu, dynamic content panels, and comprehensive admin tools
 * Supports vehicle management, user management, booking approvals, and reporting
 */
package view;

import java.awt.Image;
import javax.swing.ImageIcon;
import model.User;

/**
 * AdminDashboard - Main administrative interface for the vehicle rental system
 * Provides centralized access to all administrative functions including:
 * - Dashboard overview with key metrics
 * - Vehicle fleet management
 * - User account management
 * - Booking approval workflow
 * - System reports and analytics
 * - Administrative settings
 *
 * @author Pacifique Harerimana
 */
public class AdminDashboard extends javax.swing.JFrame {
    
    
    /** Currently logged in administrator user */
    private User loggedInUser;

    /**
     * Default constructor - Creates new AdminDashboard without user context
     * Delegates to parameterized constructor with null user
     */
    public AdminDashboard() {
        this(null); // Call the parameterized constructor with null
    }
    
    /**
     * Parameterized constructor - Creates AdminDashboard with user context
     * Initializes the dashboard interface and loads default home panel
     * 
     * @param user The administrator user accessing the dashboard
     */
    public AdminDashboard(User user) {
        initComponents();
        this.setSize(1400, 700);                    // Set optimal window size
        this.setLocationRelativeTo(null);           // Center on screen
        this.loggedInUser = user;                   // Store user context
        
        // Set application icon
        setIconImage(new ImageIcon("images/logo.png").getImage());   
        
        // Load and scale company logo for display
        ImageIcon logo = new ImageIcon("images/logo.png");
        Image img = logo.getImage().getScaledInstance(120, 43, Image.SCALE_SMOOTH);
        imageLabel.setIcon(new ImageIcon(img));
        
        // Display admin home panel by default (no RMI connections)
        showPage(new AdminHomePanel());
    }

    /**
     * Displays a panel in the main content area
     * Replaces current content with the specified panel and refreshes display
     * 
     * @param page The panel to display in the content area
     */
    private void showPage(javax.swing.JPanel page) {
        panelContent.removeAll();                                    // Clear existing content
        panelContent.setLayout(new java.awt.BorderLayout());        // Set layout manager
        panelContent.add(page, java.awt.BorderLayout.CENTER);       // Add new panel

        // Refresh display to show new content
        page.revalidate();
        page.repaint();
        panelContent.revalidate();
        panelContent.repaint();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        btnManageVehicle = new javax.swing.JButton();
        btnManageUsers = new javax.swing.JButton();
        btnBookingsApproval = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnSettings = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();
        btnReports = new javax.swing.JButton();
        titlePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMenu.setBackground(new java.awt.Color(255, 255, 255));

        btnManageVehicle.setText("Manage Vehicle");
        btnManageVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageVehicleActionPerformed(evt);
            }
        });

        btnManageUsers.setText("Manage Users");
        btnManageUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageUsersActionPerformed(evt);
            }
        });

        btnLogout.setText("LOGOUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnSettings.setText("Settings");
        btnSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel1.setText("H  A  P  A");

        btnBookingsApproval.setText("Bookings Approval");
        btnBookingsApproval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookingsApprovalActionPerformed(evt);
            }
        });

        btnReports.setText("Reports");
        btnReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsActionPerformed(evt);
            }
        });

        // Add Dashboard button programmatically (not in form design)
        btnDashboard = new javax.swing.JButton();
        btnDashboard.setText("Dashboard");
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addGap(0, 43, Short.MAX_VALUE)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnReports, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBookingsApproval, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(89, 89, 89)
                .addComponent(btnDashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnManageVehicle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnManageUsers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBookingsApproval)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReports)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSettings)
                .addGap(18, 18, 18)
                .addComponent(btnLogout)
                .addGap(24, 24, 24))
        );

        titlePanel.setBackground(new java.awt.Color(8, 153, 73));

        jLabel2.setFont(new java.awt.Font("Cooper Black", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Admin Dashboard");

        jLabel3.setFont(new java.awt.Font("Perpetua", 0, 23)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Complete system management and control");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelContentLayout = new javax.swing.GroupLayout(panelContent);
        panelContent.setLayout(panelContentLayout);
        panelContentLayout.setHorizontalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelContentLayout.setVerticalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 642, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setResizable(true);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Dashboard button click handler
     * Displays the admin home panel with system overview and metrics
     * 
     * @param evt Action event from button click
     */
    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {
        showPage(new AdminHomePanel());
    }

    /**
     * Manage Vehicle button click handler
     * Displays the vehicle management panel for fleet administration
     * 
     * @param evt Action event from button click
     */
    private void btnManageVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageVehicleActionPerformed
        showPage(new ManageVehiclesPanel());
    }//GEN-LAST:event_btnManageVehicleActionPerformed

    /**
     * Manage Users button click handler
     * Displays the user management panel for customer and admin account administration
     * 
     * @param evt Action event from button click
     */
    private void btnManageUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageUsersActionPerformed
         showPage(new ManageUsersPanel());
    }//GEN-LAST:event_btnManageUsersActionPerformed

    /**
     * Logout button click handler
     * Logs out the current administrator and returns to login screen
     * 
     * @param evt Action event from button click
     */
    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        new LoginForm().setVisible(true);    // Show login form
        this.dispose();                      // Close admin dashboard
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * Settings button click handler
     * Displays the settings panel for administrator account management
     * 
     * @param evt Action event from button click
     */
    private void btnSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingsActionPerformed
        showPage(new SettingsPanel(loggedInUser));
    }//GEN-LAST:event_btnSettingsActionPerformed

    /**
     * Bookings Approval button click handler
     * Displays the booking approval panel for managing customer booking requests
     * 
     * @param evt Action event from button click
     */
    private void btnBookingsApprovalActionPerformed(java.awt.event.ActionEvent evt) {
        showPage(new BookingsApprovalPanel());
    }

    /**
     * Reports button click handler
     * Displays the reports panel for system analytics and business intelligence
     * 
     * @param evt Action event from button click
     */
    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        showPage(new AdminReportsPanel());
    }//GEN-LAST:event_btnReportsActionPerformed

    // UI Component Variables - Generated by NetBeans Form Editor
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookingsApproval;    // Navigation button for booking approvals
    private javax.swing.JButton btnDashboard;           // Navigation button for dashboard home
    private javax.swing.JButton btnLogout;              // Logout button
    private javax.swing.JButton btnManageUsers;         // Navigation button for user management
    private javax.swing.JButton btnManageVehicle;       // Navigation button for vehicle management
    private javax.swing.JButton btnReports;             // Navigation button for reports
    private javax.swing.JButton btnSettings;            // Navigation button for settings
    private javax.swing.JLabel imageLabel;              // Company logo display label
    private javax.swing.JLabel jLabel1;                 // Company name label
    private javax.swing.JLabel jLabel2;                 // Main title label
    private javax.swing.JLabel jLabel3;                 // Subtitle label
    private javax.swing.JPanel panelContent;            // Main content area for dynamic panels
    private javax.swing.JPanel panelMenu;               // Left navigation menu panel
    private javax.swing.JPanel titlePanel;              // Top title banner panel
    // End of variables declaration//GEN-END:variables
}