/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import javax.swing.JOptionPane;
import model.*;
import service.*;

/**
 *
 * @author Pacifique Harerimana
 */
public class BlockCardDialog1 extends javax.swing.JFrame {

    public BlockCardDialog1() {
        initComponents();
        setLocationRelativeTo(null);
        
        blockCardBtn.addActionListener(e -> blockCard());
        cancelBtn.addActionListener(e -> dispose());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        blockCardBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        cardNumberTxt = new javax.swing.JTextField();
        checkCardBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cardInfoTxt = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BLOCK CARD");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("BLOCK CUSTOMER CARD");

        jLabel2.setText("Card Number:");

        blockCardBtn.setText("BLOCK CARD");

        cancelBtn.setText("CANCEL");

        checkCardBtn.setText("Check Card");
        checkCardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCardBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Card Info: --");

        jLabel3.setText("Customer reports lost/stolen card ");

        jLabel5.setText("Enter card number to deactivate");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cardInfoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkCardBtn)
                            .addComponent(cardNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(blockCardBtn)
                            .addGap(26, 26, 26)
                            .addComponent(cancelBtn)
                            .addGap(58, 58, 58))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(135, 135, 135)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(checkCardBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(cardInfoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blockCardBtn)
                    .addComponent(cancelBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkCardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCardBtnActionPerformed
        checkCard();
    }//GEN-LAST:event_checkCardBtnActionPerformed

    private void checkCard() {
        String cardNumber = cardNumberTxt.getText().trim();
        if(cardNumber.isEmpty()){
            JOptionPane.showMessageDialog(this, "Enter card number!");
            return;
        }
        
        try{
            Registry registry = LocateRegistry.getRegistry("127.0.0.1", 3000);
            CardService service = (CardService)registry.lookup("card");
            Card card = new Card(cardNumber);
            card = service.searchCardById(card);
            
            if(card != null){
                String status = card.isActive() ? "ACTIVE" : "BLOCKED";
                cardInfoTxt.setText("Type: " + card.getType() + " | Status: " + status);
                if(!card.isActive()){
                    JOptionPane.showMessageDialog(this, "Card is already blocked!");
                }
            }else{
                cardInfoTxt.setText("");
                JOptionPane.showMessageDialog(this, "Card not found!");
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }
    
    private void blockCard() {
        String cardNumber = cardNumberTxt.getText().trim();
        if(cardNumber.isEmpty()){
            JOptionPane.showMessageDialog(this, "Enter card number!");
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to BLOCK this card?\nThis action will deactivate the card.",
            "Confirm Block",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);
        
        if(confirm != JOptionPane.YES_OPTION) return;
        
        try{
            Registry registry = LocateRegistry.getRegistry("127.0.0.1", 3000);
            CardService service = (CardService)registry.lookup("card");
            Card card = new Card(cardNumber);
            card = service.searchCardById(card);
            
            if(card != null){
                card.setActive(false);
                Card result = service.updateCard(card);
                
                if(result != null){
                    JOptionPane.showMessageDialog(this,
                        "CARD BLOCKED SUCCESSFULLY!\n\n" +
                        "Card Number: " + result.getCardNumber() + "\n" +
                        "Status: BLOCKED\n\n" +
                        "Card is now deactivated.",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                }
            }else{
                JOptionPane.showMessageDialog(this, "Card not found!");
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BlockCardDialog1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BlockCardDialog1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BlockCardDialog1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BlockCardDialog1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BlockCardDialog1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blockCardBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel cardInfoTxt;
    private javax.swing.JTextField cardNumberTxt;
    private javax.swing.JButton checkCardBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
