/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import javax.swing.JOptionPane;
import model.*;
import service.*;

/**
 *
 * @author Pacifique Harerimana
 */
public class IssueCardDialog1 extends javax.swing.JFrame {

    public IssueCardDialog1() {
        initComponents();
        setLocationRelativeTo(null);
        
        cancelBtn.addActionListener(e -> dispose());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        firstnameTxt = new javax.swing.JTextField();
        cardnumberTxt = new javax.swing.JTextField();
        ccvTxt = new javax.swing.JTextField();
        expiryMonthTxt = new javax.swing.JTextField();
        pinTxt = new javax.swing.JTextField();
        cardTypeCombo = new javax.swing.JComboBox<>();
        issueCardBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        expiryYearTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ISSUE CARD");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("ISSUE CARD TO CUSTOMER");

        jLabel2.setText("Account Number:");

        jLabel3.setText("Card Number (16 digits):");

        jLabel4.setText("Card Type:");

        jLabel5.setText("CCV (3 digits)");

        jLabel6.setText("PIN (4 digits):");

        jLabel7.setText("Expiry Month (MM):");

        jLabel8.setText("Expiry Year (YYYY):");

        cardTypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DEBIT", "CREDIT", "VISA", "PRE_PAID" }));

        issueCardBtn.setText("ISSUE CARD");
        issueCardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueCardBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("CANCEL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(expiryMonthTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ccvTxt)
                            .addComponent(cardnumberTxt)
                            .addComponent(firstnameTxt)
                            .addComponent(pinTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(cardTypeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(expiryYearTxt))))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(issueCardBtn)
                .addGap(18, 18, 18)
                .addComponent(cancelBtn)
                .addGap(78, 78, 78))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(firstnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cardnumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cardTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ccvTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(pinTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(expiryMonthTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(expiryYearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn)
                    .addComponent(issueCardBtn))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void issueCardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueCardBtnActionPerformed
        issueCard();
    }//GEN-LAST:event_issueCardBtnActionPerformed

    private void issueCard() {
        if(firstnameTxt.getText().trim().isEmpty() || cardnumberTxt.getText().trim().isEmpty() ||
           ccvTxt.getText().trim().isEmpty() || pinTxt.getText().trim().isEmpty() ||
           expiryMonthTxt.getText().trim().isEmpty() || expiryYearTxt.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "All fields required!");
            return;
        }
        
        if(!cardnumberTxt.getText().matches("\\d{16}")){
            JOptionPane.showMessageDialog(this, "Card number must be 16 digits!");
            return;
        }
        
        if(!ccvTxt.getText().matches("\\d{3}")){
            JOptionPane.showMessageDialog(this, "CCV must be 3 digits!");
            return;
        }
        
        if(!pinTxt.getText().matches("\\d{4}")){
            JOptionPane.showMessageDialog(this, "PIN must be 4 digits!");
            return;
        }
        
        try{
            Registry registry = LocateRegistry.getRegistry("127.0.0.1", 3000);
            CardService service = (CardService)registry.lookup("card");
            
            Card card = new Card();
            card.setCardNumber(cardnumberTxt.getText().trim());
            card.setType(ECardType.valueOf(cardTypeCombo.getSelectedItem().toString()));
            card.setCcv(ccvTxt.getText().trim());
            card.setPin(pinTxt.getText().trim());
            card.setEndMonth(expiryMonthTxt.getText().trim());
            card.setEndYear(expiryYearTxt.getText().trim());
            card.setActive(true);
            Account account = new Account(firstnameTxt.getText().trim());
            card.setAccount(account);
            
            Card result = service.registerCard(card);
            
            if(result != null){
                JOptionPane.showMessageDialog(this,
                    "CARD ISSUED SUCCESSFULLY!\n\n" +
                    "Card Number: " + result.getCardNumber() + "\n" +
                    "Type: " + result.getType() + "\n" +
                    "PIN: " + result.getPin() + "\n" +
                    "Expiry: " + result.getEndMonth() + "/" + result.getEndYear() + "\n\n" +
                    "Give card to customer!",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);
                dispose();
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueCardDialog1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueCardDialog1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueCardDialog1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueCardDialog1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssueCardDialog1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JComboBox<String> cardTypeCombo;
    private javax.swing.JTextField cardnumberTxt;
    private javax.swing.JTextField ccvTxt;
    private javax.swing.JTextField expiryMonthTxt;
    private javax.swing.JTextField expiryYearTxt;
    private javax.swing.JTextField firstnameTxt;
    private javax.swing.JButton issueCardBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField pinTxt;
    // End of variables declaration//GEN-END:variables
}
