/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import model.*;
import service.*;

/**
 *
 * @author Pacifique Harerimana
 */
public class LoanRequestDialog1 extends javax.swing.JFrame {

    public LoanRequestDialog1() {
        initComponents();
        setLocationRelativeTo(null);
        
        approveLoanBtn.addActionListener(e -> approveLoan());
        cancelBtn.addActionListener(e -> dispose());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        approveLoanBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        accountNumberTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        loanAmountTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        interestRatetxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        loanPeriodTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REQUEST LOAN");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("CUSTOMER LOAN APPLICATION");

        jLabel2.setText("Account Number:");

        approveLoanBtn.setText("APPROVE LOAN");

        cancelBtn.setText("CANCEL");

        jLabel5.setText("Loan Amount:");

        jLabel6.setText("Interest rate (%):");

        interestRatetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interestRatetxtActionPerformed(evt);
            }
        });

        jLabel7.setText("Loan Period (months):");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(135, 135, 135))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(loanAmountTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                .addComponent(accountNumberTxt))
                            .addComponent(interestRatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loanPeriodTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(approveLoanBtn)
                        .addGap(68, 68, 68)
                        .addComponent(cancelBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(accountNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(loanAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(interestRatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(loanPeriodTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn)
                    .addComponent(approveLoanBtn))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void interestRatetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interestRatetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interestRatetxtActionPerformed

    private void approveLoan() {
        if(accountNumberTxt.getText().trim().isEmpty() || loanAmountTxt.getText().trim().isEmpty() ||
           interestRatetxt.getText().trim().isEmpty() || loanPeriodTxt.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "All fields required!");
            return;
        }
        
        try{
            double amount = Double.parseDouble(loanAmountTxt.getText().trim());
            double rate = Double.parseDouble(interestRatetxt.getText().trim());
            int months = Integer.parseInt(loanPeriodTxt.getText().trim());
            
            Registry registry = LocateRegistry.getRegistry("127.0.0.1", 3000);
            AccountService accService = (AccountService)registry.lookup("account");
            Account acc = new Account(accountNumberTxt.getText().trim());
            Account account = accService.searchAccountById(acc);
            if(account == null){
                JOptionPane.showMessageDialog(this, "Account not found!");
                return;
            }
            
            LoanService service = (LoanService)registry.lookup("loan");
            Loan loan = new Loan();
            loan.setAmountToReceive(amount);
            loan.setInterestRate(rate);
            loan.setStartDate(LocalDate.now());
            loan.setEndDate(LocalDate.now().plusMonths(months));
            java.util.Set<Account> accounts = new java.util.HashSet<>();
            accounts.add(account);
            loan.setAccounts(accounts);
            
            Loan result = service.registerLoan(loan);
            
            if(result != null){
                JOptionPane.showMessageDialog(this,
                    "LOAN APPROVED!\n\n" +
                    "Loan Amount: $" + result.getAmountToReceive() + "\n" +
                    "Total to Pay: $" + result.getAmountToPay() + "\n" +
                    "Monthly Payment: $" + result.getMonthlyDeduction() + "\n" +
                    "Period: " + months + " months",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);
                dispose();
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanRequestDialog1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanRequestDialog1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanRequestDialog1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanRequestDialog1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanRequestDialog1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountNumberTxt;
    private javax.swing.JButton approveLoanBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField interestRatetxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField loanAmountTxt;
    private javax.swing.JTextField loanPeriodTxt;
    // End of variables declaration//GEN-END:variables
}
