/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import model.*;
import service.*;

/**
 *
 * @author Pacifique Harerimana
 */
public class LoanPaymentDialog1 extends javax.swing.JFrame {

    public LoanPaymentDialog1() {
        initComponents();
        setLocationRelativeTo(null);
        recorPaymentBtn.setEnabled(false);
        recorPaymentBtn.addActionListener(e -> recordPayment());
        cancelBtn.addActionListener(e -> dispose());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        recorPaymentBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        loanIdTxt = new javax.swing.JTextField();
        paymentAmountTxt = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        loanInfoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOAN PAYMENT");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("RECORD LOAN PAYMENT");

        jLabel2.setText("Account Number:");
        jLabel3.setText("Loan Details:");
        jLabel4.setText("Payment Amount:");

        recorPaymentBtn.setText("RECORD PAYMENT");
        cancelBtn.setText("CANCEL");
        
        searchBtn.setText("Search Loan");
        searchBtn.addActionListener(e -> searchLoan());
        loanInfoLabel.setText("---");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loanIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(searchBtn))
                    .addComponent(loanInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paymentAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(135, 135, 135))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(recorPaymentBtn)
                        .addGap(28, 28, 28)
                        .addComponent(cancelBtn)
                        .addGap(52, 52, 52))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(loanIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(loanInfoLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(paymentAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn)
                    .addComponent(recorPaymentBtn))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Loan currentLoan = null;
    
    private void searchLoan() {
        String accNum = loanIdTxt.getText().trim();
        if(accNum.isEmpty()){
            JOptionPane.showMessageDialog(this, "Enter account number!");
            return;
        }
        
        try{
            Registry registry = LocateRegistry.getRegistry("127.0.0.1", 3000);
            AccountService accService = (AccountService)registry.lookup("account");
            Account acc = new Account(accNum);
            Account account = accService.getAccountWithDetails(acc);
            
            if(account == null){
                JOptionPane.showMessageDialog(this, "Account not found!");
                return;
            }
            
            if(account.getLoans() == null || account.getLoans().isEmpty()){
                JOptionPane.showMessageDialog(this, "No loans found for this account!");
                loanInfoLabel.setText("No loans");
                return;
            }
            
            currentLoan = null;
            for(Loan loan : account.getLoans()){
                if(loan.getStatus() != ELoanStatus.COMPLETED){
                    currentLoan = loan;
                    break;
                }
            }
            
            if(currentLoan == null){
                JOptionPane.showMessageDialog(this, "All loans are completed!");
                loanInfoLabel.setText("All loans completed");
                return;
            }
            
            double paid = 0;
            if(currentLoan.getRepayments() != null){
                for(LoanRepayment rep : currentLoan.getRepayments()){
                    paid += rep.getPaymentAmount();
                }
            }
            double remaining = currentLoan.getAmountToPay() - paid;
            
            loanInfoLabel.setText("Loan ID: " + currentLoan.getId() + " | Total: $" + currentLoan.getAmountToPay() + " | Remaining: $" + remaining);
            recorPaymentBtn.setEnabled(true);
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }
    
    private void recordPayment() {
        if(currentLoan == null){
            JOptionPane.showMessageDialog(this, "Search for a loan first!");
            return;
        }
        
        if(paymentAmountTxt.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Enter payment amount!");
            return;
        }
        
        try{
            double amount = Double.parseDouble(paymentAmountTxt.getText().trim());
            
            if(amount <= 0){
                JOptionPane.showMessageDialog(this, "Payment amount must be greater than zero!");
                return;
            }
            
            Registry registry = LocateRegistry.getRegistry("127.0.0.1", 3000);
            LoanRepaymentService service = (LoanRepaymentService)registry.lookup("loanRepayment");
            
            LoanRepayment payment = new LoanRepayment();
            payment.setPaymentAmount(amount);
            payment.setPaymentDate(LocalDate.now());
            payment.setLoan(currentLoan);
            
            LoanRepayment result = service.registerLoanRepayment(payment);
            
            if(result != null){
                JOptionPane.showMessageDialog(this,
                    "PAYMENT RECORDED!\n\n" +
                    "Amount: $" + amount + "\n" +
                    "Date: " + LocalDate.now(),
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);
                dispose();
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanPaymentDialog1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanPaymentDialog1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanPaymentDialog1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanPaymentDialog1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanPaymentDialog1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField loanIdTxt;
    private javax.swing.JTextField paymentAmountTxt;
    private javax.swing.JButton recorPaymentBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JLabel loanInfoLabel;
    // End of variables declaration//GEN-END:variables
}
